### ISSUE TITLE
js_variables_objects feedback

### ISSUE THREAD

**Issue by mlweiss** [hilarybarr/phase_0_unit_1#8]
Hey Hilary,

As always enjoyed reading your reflection. It seems like you really grappled with the topics and were able to identify what was causing you trouble. I also thought your re-factored code looked good! It seems like you got a better understanding of arrays after this challenge. I would recommend you also look into some of the methods like .push and .pop as well. 

Great job!

**Comment by hilarybarr** [comment]
Thank you so much for the feedback Michael :-)
